Recording and playing .wav files
TheKamCzer/MetodykiProjektowTeleinf pull request #7
Opened 2019-12-07 20:18 UTC by Wericzek

2019-12-07 20:35 UTC, Camcore95 commented on Main.py
> +#from Record_Play import Play_UT
jeżeli nie potrzebne to usuń, nie rób śmieci w kodzie

2019-12-07 20:35 UTC, Camcore95 commented on Main.py
> +#Demodulator_UT.shouldDemodulateMostOfInputBitsWithNoise()
czemu zakomentowałaś te testy?

2019-12-07 20:36 UTC, Camcore95 commented on Record_Play/Player.py
> +        self.p = p
magic val - samo p nic nie mówi, nadaj jakąś w miarę sensowną nazwe, żeby potem było wiadomo co to jest

2019-12-07 20:37 UTC, Camcore95 commented on Record_Play/Player.py
> +        self.wf = wf
jak wyżej

2019-12-07 20:38 UTC, Camcore95 commented on Record_Play/Recorder.py
> +        self.p = p
jak wyżej

2019-12-07 20:45 UTC, Camcore95 requested changes

2019-12-07 20:45 UTC, Camcore95 commented on Record_Play/Recorder_UT.py
> +frames = []  # Initialize array to store frames
INFO: Ja używałem wielkich liter jeżeli chodzi o "stałe", więc możesz w sumie też tak zrobić :)

2019-12-07 20:45 UTC, Camcore95 commented on Main.py
> +#from Record_Play import Play_UT
> 
> 
> jeżeli nie potrzebne to usuń, nie rób śmieci w kodzie

2019-12-07 20:45 UTC, Camcore95 commented on Main.py
> +#Demodulator_UT.shouldDemodulateMostOfInputBitsWithNoise()
> 
> 
> czemu zakomentowałaś te testy?

2019-12-07 20:45 UTC, Camcore95 commented on Record_Play/Player.py
> +        self.p = p
> 
> 
> magic val - samo p nic nie mówi, nadaj jakąś w miarę sensowną nazwe, żeby potem było wiadomo co to jest

2019-12-07 20:45 UTC, Camcore95 commented on Record_Play/Player.py
> +        self.wf = wf
> 
> 
> jak wyżej

2019-12-07 20:45 UTC, Camcore95 commented on Record_Play/Recorder.py
> +        self.p = p
> 
> 
> jak wyżej

2019-12-07 20:45 UTC, Camcore95 commented on Record_Play/Recorder_UT.py
> +frames = []  # Initialize array to store frames
w sumie to ganie ogólne info do całego review

2019-12-15 11:55 UTC, mgadek007 commented
Do poprawy :D

2019-12-15 11:55 UTC, closed without merging